//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deneme {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Deneme.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Bu türü kesin olarak belirtilmiş kaynak sınıfını kullanarak geçerli iş parçacığının
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Hesap  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Böyle bir mail adresi bulunamadı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AccountNotFound {
            get {
                return ResourceManager.GetString("AccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hesabınız başarıyla aktifleştirildi. Giriş yapmak için tıklayınız : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ActivatedAccount {
            get {
                return ResourceManager.GetString("ActivatedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oluşturduğunuz BA-BS ŞABLON ile uyumlu olan bir EXCEL dosyası yükleyiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AddBaBsExcel {
            get {
                return ResourceManager.GetString("AddBaBsExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oluşturduğunuz CARİ BİLGİLERİ ŞABLONU ile uyumlu bir EXCEL dosyası yükleyiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AddCurrentExcel {
            get {
                return ResourceManager.GetString("AddCurrentExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oluşturduğunuz CARİ MUTABAKAT ŞABLONU ile uyumlu bir EXCEL dosyası yükleyiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AddCurrentReconciliationExcel {
            get {
                return ResourceManager.GetString("AddCurrentReconciliationExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen şirket bilgilerini yıldızlı alanlar boş kalmayacak şekilde doldurunuz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AddEditCompany {
            get {
                return ResourceManager.GetString("AddEditCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oluşturduğunuz FATURA ŞABLONU ile uyumlu bir EXCEL dosyası yükleyiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AddInvoiceExcel {
            get {
                return ResourceManager.GetString("AddInvoiceExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ba-Bs Mutabakat bilgileri ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AddReconciliationDetails {
            get {
                return ResourceManager.GetString("AddReconciliationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yüklediğiniz faturalardan mutabakat oluşturunuz.. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AddReconciliationExcel {
            get {
                return ResourceManager.GetString("AddReconciliationExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adres benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adres benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Adres {
            get {
                return ResourceManager.GetString("Adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şifrenizi yenilemek için aşağıdaki butona tıklayınız. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AlertPasswordMail {
            get {
                return ResourceManager.GetString("AlertPasswordMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Onaylandı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Onaylanan Mutabakatlar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ApprovedReconciliations {
            get {
                return ResourceManager.GetString("ApprovedReconciliations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yetkilendir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Authorize {
            get {
                return ResourceManager.GetString("Authorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yetkili benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Authorized {
            get {
                return ResourceManager.GetString("Authorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ay benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Ay {
            get {
                return ResourceManager.GetString("Ay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Anasayfaya geri dön benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BackToHome {
            get {
                return ResourceManager.GetString("BackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Giriş sayfasına geri dön. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BackToLogin {
            get {
                return ResourceManager.GetString("BackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ba Oluştur benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BaCreate {
            get {
                return ResourceManager.GetString("BaCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başlangıç Satırı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BaşlangıçSatırı {
            get {
                return ResourceManager.GetString("BaşlangıçSatırı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Belge Numarası benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BelgeNumarası {
            get {
                return ResourceManager.GetString("BelgeNumarası", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Belge Sayısı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BelgeSayısı {
            get {
                return ResourceManager.GetString("BelgeSayısı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Belge Tarihi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BelgeTarihi {
            get {
                return ResourceManager.GetString("BelgeTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cari Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CariAdı {
            get {
                return ResourceManager.GetString("CariAdı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cari İl benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Cariİl {
            get {
                return ResourceManager.GetString("Cariİl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cari Kodu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CariKodu {
            get {
                return ResourceManager.GetString("CariKodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şifreniz başarıyla değiştirildi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ChangedSuccesfully {
            get {
                return ResourceManager.GetString("ChangedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şifre Değiştir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya Seç benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İl benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tıklandı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Clicked {
            get {
                return ResourceManager.GetString("Clicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Firma Kodu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CompanyCode {
            get {
                return ResourceManager.GetString("CompanyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şirket İşlemleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CompanyOp {
            get {
                return ResourceManager.GetString("CompanyOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şirket İşlemleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CompanyOperations {
            get {
                return ResourceManager.GetString("CompanyOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şirket başarıyla seçildi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CompanySelectedSuccesfully {
            get {
                return ResourceManager.GetString("CompanySelectedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şirket Ünvanı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CompanyTitle {
            get {
                return ResourceManager.GetString("CompanyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *Şifre eşleşmemektedir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Onay Durumu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ConfirmationStatus {
            get {
                return ResourceManager.GetString("ConfirmationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şifreyi Yinele benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ülke benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oluştur benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Excelden Mutabakat Oluştur benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CreateReconciliationfromExcel {
            get {
                return ResourceManager.GetString("CreateReconciliationfromExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Faturadan Mutabakat Oluştur benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CreateReconciliationfromInvoice {
            get {
                return ResourceManager.GetString("CreateReconciliationfromInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı Hesabı Oluşturunuz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CreateUserAccount {
            get {
                return ResourceManager.GetString("CreateUserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cari Kodu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CurrentCode {
            get {
                return ResourceManager.GetString("CurrentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cari Bilgileri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CurrentInformations {
            get {
                return ResourceManager.GetString("CurrentInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cari Bigi Şablonu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CurrentInformationTemplate {
            get {
                return ResourceManager.GetString("CurrentInformationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cari Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CurrentName {
            get {
                return ResourceManager.GetString("CurrentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cari Sayısı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CurrentNumber {
            get {
                return ResourceManager.GetString("CurrentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cari Mutabakat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CurrentReconciliation {
            get {
                return ResourceManager.GetString("CurrentReconciliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cari Mutabakat Şablonu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CurrentReconciliationTemplate {
            get {
                return ResourceManager.GetString("CurrentReconciliationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cari İl benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CurrentState {
            get {
                return ResourceManager.GetString("CurrentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cari Tipi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CurrentType {
            get {
                return ResourceManager.GetString("CurrentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sectiğiniz kaydı silmek istediğinize emin misiniz ? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kayıt başarıyla silindi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeletedSuccessfully {
            get {
                return ResourceManager.GetString("DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İletildi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Delivered {
            get {
                return ResourceManager.GetString("Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detay benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ba-Bs Excel Yukleme benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DialogBaBs {
            get {
                return ResourceManager.GetString("DialogBaBs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şirket İşlemleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DialogCompanyOperations {
            get {
                return ResourceManager.GetString("DialogCompanyOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cari Bilgileri Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DialogCurrentDetails {
            get {
                return ResourceManager.GetString("DialogCurrentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fatura Bilgileri Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DialogInvoice {
            get {
                return ResourceManager.GetString("DialogInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alt Kullanıcı İşlemleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DialogSubUser {
            get {
                return ResourceManager.GetString("DialogSubUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bilgilerimi Duzenle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DialogUserOp {
            get {
                return ResourceManager.GetString("DialogUserOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Belge Tarihi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DocumentDate {
            get {
                return ResourceManager.GetString("DocumentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Belge Sayısı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DocumentNumber {
            get {
                return ResourceManager.GetString("DocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Döviz Tipi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DövizTipi {
            get {
                return ResourceManager.GetString("DövizTipi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yükle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Düzenle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E-posta benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email1 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Email1 {
            get {
                return ResourceManager.GetString("Email1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email2 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Email2 {
            get {
                return ResourceManager.GetString("Email2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email Detay benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EmailDetail {
            get {
                return ResourceManager.GetString("EmailDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bu email adresi zaten kullanılmaktadır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EmailExist {
            get {
                return ResourceManager.GetString("EmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email Durumu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EmailStatus {
            get {
                return ResourceManager.GetString("EmailStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kayıt bulunamadı.:( benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EmptyTable {
            get {
                return ResourceManager.GetString("EmptyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Veri bulunamadı, Lütfen  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EmptyTable1 {
            get {
                return ResourceManager.GetString("EmptyTable1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   butonuna tıklayınız. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EmptyTable2 {
            get {
                return ResourceManager.GetString("EmptyTable2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başlangıç satırı giriniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EnterStartLine {
            get {
                return ResourceManager.GetString("EnterStartLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///    benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Entries {
            get {
                return ResourceManager.GetString("Entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hata! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Excel Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExcelName {
            get {
                return ResourceManager.GetString("ExcelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DövizTipi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExchangeType {
            get {
                return ResourceManager.GetString("ExchangeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fatura Tipi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FaturaTipi {
            get {
                return ResourceManager.GetString("FaturaTipi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FaturaTipi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FaturaTipiString {
            get {
                return ResourceManager.GetString("FaturaTipiString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fax Numarası benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FaxNumber {
            get {
                return ResourceManager.GetString("FaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen boş alanları doldurunuz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Fill {
            get {
                return ResourceManager.GetString("Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şifremi Unuttum benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///    adresine gönderildi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HasBeenSent {
            get {
                return ResourceManager.GetString("HasBeenSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Anasayfa benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geçersiz İstek benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Http400 {
            get {
                return ResourceManager.GetString("Http400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tarayıcınız geçersiz bir istek gönderdi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Http400Explanation {
            get {
                return ResourceManager.GetString("Http400Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yasak benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Http403 {
            get {
                return ResourceManager.GetString("Http403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Erişim İzniniz Bulunmamaktadır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Http403Explanation {
            get {
                return ResourceManager.GetString("Http403Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Who0ps! Sayfa bulunamadı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Http404 {
            get {
                return ResourceManager.GetString("Http404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aradığınız sayfa bulunamadı. Önceki sayfaya geri dönün veya daha fazla bilgi için Yardım Merkezimizi görüntüleyin benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Http404Explanation {
            get {
                return ResourceManager.GetString("Http404Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sunucu Hatası benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Http500 {
            get {
                return ResourceManager.GetString("Http500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Neden sayfanızı yenilemeyi denemiyorsunuz? veya destekle iletişime geçebilirsiniz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Http500Explanation {
            get {
                return ResourceManager.GetString("Http500Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bu site bir ayarlama yapıyor. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Http503 {
            get {
                return ResourceManager.GetString("Http503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Daha sonra tekrar deneyiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Http503Explanation {
            get {
                return ResourceManager.GetString("Http503Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tc Kimlik No benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string IdentificationNumber {
            get {
                return ResourceManager.GetString("IdentificationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _TOTAL_ adet girişten _START_ ile _END_ arasındakiler gösteriliyor benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0 adet kayıttan 0 ile 0 arasındakiler gösteriliyor benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string InfoEmpty {
            get {
                return ResourceManager.GetString("InfoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (_MAX_ kayıttan filtrelenmiş) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string InfoFiltered {
            get {
                return ResourceManager.GetString("InfoFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geçersiz kimlik bilgisi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string InvalidCredential {
            get {
                return ResourceManager.GetString("InvalidCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geçersiz Mail Adresi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string InvalidMail {
            get {
                return ResourceManager.GetString("InvalidMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geçersiz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string InvalidMailChart {
            get {
                return ResourceManager.GetString("InvalidMailChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geçersiz İşlem. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string InvalidRequest {
            get {
                return ResourceManager.GetString("InvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fatura Bilgileri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string InvoiceInformations {
            get {
                return ResourceManager.GetString("InvoiceInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Faturalar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Invoices {
            get {
                return ResourceManager.GetString("Invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fatura Aktarım Şablonu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string InvoiceTransferTemplate {
            get {
                return ResourceManager.GetString("InvoiceTransferTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fatura Tipi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string InvoiceType {
            get {
                return ResourceManager.GetString("InvoiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İşlem, başka bir işlem tarafından kullanılıyor. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string IOExeption {
            get {
                return ResourceManager.GetString("IOExeption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kdv Hariç Tutar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string KdvHariçTutar {
            get {
                return ResourceManager.GetString("KdvHariçTutar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kdv Tutarı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string KdvTutarı {
            get {
                return ResourceManager.GetString("KdvTutarı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dil Ayarları benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LanguageSettings {
            get {
                return ResourceManager.GetString("LanguageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Son Ba Mutabakat Tarihi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LastBoughtReconciliationDate {
            get {
                return ResourceManager.GetString("LastBoughtReconciliationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Son Cari Mutabakat Tarihi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LastCurrentReconciliationDate {
            get {
                return ResourceManager.GetString("LastCurrentReconciliationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Son Bs Mutabakat Tarihi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LastSoldReconciliationDate {
            get {
                return ResourceManager.GetString("LastSoldReconciliationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sayfa başına _MENU_ adet kayıt göster benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LengthMenu {
            get {
                return ResourceManager.GetString("LengthMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yükleniyor... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LoadingRecords {
            get {
                return ResourceManager.GetString("LoadingRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Giriş Yap benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Giriş Yapın benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LoginHeader {
            get {
                return ResourceManager.GetString("LoginHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çıkış Yap benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mail başarıyla gönderildi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MailSent {
            get {
                return ResourceManager.GetString("MailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cari bilgileri eksik.  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MissingCurrentInformations {
            get {
                return ResourceManager.GetString("MissingCurrentInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ay benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profilim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeni Şifre benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sonraki benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya Seçilmedi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NoFile {
            get {
                return ResourceManager.GetString("NoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Onaylanmadı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NotApproved {
            get {
                return ResourceManager.GetString("NotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Onaylanmayan Mutabakatlar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NotApprovedReconciliations {
            get {
                return ResourceManager.GetString("NotApprovedReconciliations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eski Şifre benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Girmiş olduğunuz eski şifre hatalı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string OldPasswordIncorrect {
            get {
                return ResourceManager.GetString("OldPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oluşturma Tarihi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string OluşturmaTarihi {
            get {
                return ResourceManager.GetString("OluşturmaTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şifre benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *Şifre en az 6 karakterden oluşmalı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PasswordMinLength {
            get {
                return ResourceManager.GetString("PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Beklemede benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bekleyen Mutabakatlar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PendingReconciliations {
            get {
                return ResourceManager.GetString("PendingReconciliations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GSM benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geçersiz telefon numarası. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PhoneNumberInvalid {
            get {
                return ResourceManager.GetString("PhoneNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Please {
            get {
                return ResourceManager.GetString("Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Önceki benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ba-Bs Mutabakat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Reconciliation {
            get {
                return ResourceManager.GetString("Reconciliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ba-Bs Mutabakat Şablonu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ReconciliationTemplate {
            get {
                return ResourceManager.GetString("ReconciliationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mutabakat Tipi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ReconciliationType {
            get {
                return ResourceManager.GetString("ReconciliationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kayıt işlemi başarıyla tamamlandı. Hesap aktifleştirme linki  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string RegDone {
            get {
                return ResourceManager.GetString("RegDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kayıt Ol benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Beni Hatırla benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zaten bir kullanıcı hesabım var benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Reminder1 {
            get {
                return ResourceManager.GetString("Reminder1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı hesabım yok benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Reminder2 {
            get {
                return ResourceManager.GetString("Reminder2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *Bu alan boş bırakılamaz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şifreyi sıfırlama bağlantısı için bir mail adresi giriniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ResetHeader {
            get {
                return ResourceManager.GetString("ResetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şifreyi Sıfırla benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parola sıfırlama linki mail adresinize gönderilmiştir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ResetPasswordLink {
            get {
                return ResourceManager.GetString("ResetPasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şifremi Sıfırla benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ResetPasswordMailButton {
            get {
                return ResourceManager.GetString("ResetPasswordMailButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şablon Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ŞablonAdı {
            get {
                return ResourceManager.GetString("ŞablonAdı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kaydet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kayıt başarıyla kaydedildi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SavedSuccessfully {
            get {
                return ResourceManager.GetString("SavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kayıt işlemi sırasında bir sorun oluştu. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SaveProblem {
            get {
                return ResourceManager.GetString("SaveProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ara: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///    benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sütununu seçiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Select2 {
            get {
                return ResourceManager.GetString("Select2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şirket seç. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SelectCompany {
            get {
                return ResourceManager.GetString("SelectCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen bir dosya seçiniz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fatura seçiniz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SelectInvoice {
            get {
                return ResourceManager.GetString("SelectInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fatura kesim ayını seçiniz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SelectInvoiceMonth {
            get {
                return ResourceManager.GetString("SelectInvoiceMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fatura tipini seçiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SelectInvoiceType {
            get {
                return ResourceManager.GetString("SelectInvoiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fatura kesim yılını seçiniz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SelectInvoiceYear {
            get {
                return ResourceManager.GetString("SelectInvoiceYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şablon Adı Seçiniz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SelectTemplateName {
            get {
                return ResourceManager.GetString("SelectTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mail Gönder benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SendMail {
            get {
                return ResourceManager.GetString("SendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sms Gönder benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SendSms {
            get {
                return ResourceManager.GetString("SendSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gönderildi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Göster benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yetkileri Göster benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ShowAuthorizations {
            get {
                return ResourceManager.GetString("ShowAuthorizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spam benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Spam {
            get {
                return ResourceManager.GetString("Spam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şablon adı belirleyiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SpecifyTemplateName {
            get {
                return ResourceManager.GetString("SpecifyTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seçilen ŞABLON ve EXCEL uyuşmamaktadır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SqlExeption {
            get {
                return ResourceManager.GetString("SqlExeption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başlangıç Satırı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string StartLine {
            get {
                return ResourceManager.GetString("StartLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İlçe benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kaydet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vergi No. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TaxNumber {
            get {
                return ResourceManager.GetString("TaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *Vergi numarası 10 haneden oluşmalı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TaxNumberMinLength {
            get {
                return ResourceManager.GetString("TaxNumberMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vergi Dairesi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TaxOffice {
            get {
                return ResourceManager.GetString("TaxOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tc Kimlik Numarası benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TcKimlikNo {
            get {
                return ResourceManager.GetString("TcKimlikNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Telefon benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Telefon {
            get {
                return ResourceManager.GetString("Telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oluşturma Tarihi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TemplateCreationDate {
            get {
                return ResourceManager.GetString("TemplateCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şablon Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TemplateName {
            get {
                return ResourceManager.GetString("TemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şablon Ayarları benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TemplateSettings {
            get {
                return ResourceManager.GetString("TemplateSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şablon Tipi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TemplateType {
            get {
                return ResourceManager.GetString("TemplateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toplam Mutabakat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TotalReconciliation {
            get {
                return ResourceManager.GetString("TotalReconciliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeni şifre başarıyla güncellendi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UpdatedPassword {
            get {
                return ResourceManager.GetString("UpdatedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kayıt başarıyla güncellendi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UpdatedSuccessfully {
            get {
                return ResourceManager.GetString("UpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yükleniyor... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İsim Soyisim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kdv Hariç Tutar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string VatExcluded {
            get {
                return ResourceManager.GetString("VatExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kdv Tutarı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string VatValue {
            get {
                return ResourceManager.GetString("VatValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vergi Dairesi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string VergiDairesi {
            get {
                return ResourceManager.GetString("VergiDairesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vergi Numarası benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string VergiNo {
            get {
                return ResourceManager.GetString("VergiNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen e-posta adresinizi doğrulayınız. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string VerifyEmail {
            get {
                return ResourceManager.GetString("VerifyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Görüntülendi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Viewed {
            get {
                return ResourceManager.GetString("Viewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya uzantısı .xls veya .xlsx olmalıdır benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string WrongFileExtension {
            get {
                return ResourceManager.GetString("WrongFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yıl benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yıl benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Yıl {
            get {
                return ResourceManager.GetString("Yıl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hiçbir eşleşen kayıt bulunamadı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ZeroRecords {
            get {
                return ResourceManager.GetString("ZeroRecords", resourceCulture);
            }
        }
    }
}
