//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaBsMutabakat
    {
        public int MutabakatId { get; set; }
        public int KullanıcıId { get; set; }
        public int CompanyId { get; set; }
        public int FaturaBilgileriId { get; set; }
        public string FaturaBilgileri { get; set; }
        public string CariSayısı { get; set; }
        public string BelgeSayısı { get; set; }
        public string OluşturmaTarihi { get; set; }
        public string Tip { get; set; }
    }
}
