//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaBsMutabakatExcel
    {
        public string CariKodu { get; set; }
        public string CariAdı { get; set; }
        public string TcKimlikNo { get; set; }
        public string VergiNo { get; set; }
        public Nullable<decimal> KdvHariçTutar { get; set; }
        public string BelgeSayısı { get; set; }
        public int MutabakatBilgileriId { get; set; }
        public int MutabakatExcelId { get; set; }
    }
}
