//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CariMutabakatDetay
    {
        public int CariMutabakatDetayId { get; set; }
        public int CariMutabakatId { get; set; }
        public string CariKodu { get; set; }
        public string CariAdı { get; set; }
        public string VergiNo { get; set; }
        public string BelgeSayısı { get; set; }
        public Nullable<decimal> KdvHariçTutar { get; set; }
        public Nullable<decimal> KdvTutarı { get; set; }
        public string MailDurumu { get; set; }
        public string OnayDurumu { get; set; }
        public string MailDetay { get; set; }
        public string MessageID { get; set; }
        public Nullable<System.Guid> MutabakatKabulLink { get; set; }
        public Nullable<System.Guid> MutabakatRetLink { get; set; }
        public string FileName { get; set; }
    }
}
