//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CariBilgileri
    {
        public int CariBilgileriId { get; set; }
        public int KullanıcıId { get; set; }
        public int CompanyId { get; set; }
        public int ŞablonId { get; set; }
        public string ExcelAdı { get; set; }
        public string OluşturmaTarihi { get; set; }
        public string ŞablonAdı { get; set; }
    }
}
