//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CariBilgileriExcel
    {
        public string CariKodu { get; set; }
        public string CariAdı { get; set; }
        public string CariTipi { get; set; }
        public string VergiDairesi { get; set; }
        public string VergiNo { get; set; }
        public string TcKimlikNo { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Cariİl { get; set; }
        public string Telefon { get; set; }
        public string Adres { get; set; }
        public string DövizTipi { get; set; }
        public int CariBilgileriId { get; set; }
        public int CariId { get; set; }
    }
}
