//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deneme.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YirmibesYazilimMutabakatEntities1 : DbContext
    {
        public YirmibesYazilimMutabakatEntities1()
            : base("name=YirmibesYazilimMutabakatEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CariBilgileri> CariBilgileri { get; set; }
        public virtual DbSet<FaturaBilgileri> FaturaBilgileri { get; set; }
        public virtual DbSet<Şablon_CariBilgileri> Şablon_CariBilgileri { get; set; }
        public virtual DbSet<Şablon_CariMutabakat> Şablon_CariMutabakat { get; set; }
        public virtual DbSet<Şablon_FaturaAktarım> Şablon_FaturaAktarım { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Şablon_Ba_BsMutabakat> Şablon_Ba_BsMutabakat { get; set; }
        public virtual DbSet<SiteUser> SiteUser { get; set; }
        public virtual DbSet<SubUser> SubUser { get; set; }
        public virtual DbSet<CariMutabakkat> CariMutabakkat { get; set; }
        public virtual DbSet<BaBsMutabakatBilgileri> BaBsMutabakatBilgileri { get; set; }
        public virtual DbSet<BaBsMutabakatDetay> BaBsMutabakatDetay { get; set; }
        public virtual DbSet<CariMutabakatDetay> CariMutabakatDetay { get; set; }
        public virtual DbSet<BaBsMutabakat> BaBsMutabakat { get; set; }
        public virtual DbSet<Yetki> Yetki { get; set; }
        public virtual DbSet<BaBsMutabakatExcel> BaBsMutabakatExcel { get; set; }
        public virtual DbSet<CariBilgileriExcel> CariBilgileriExcel { get; set; }
        public virtual DbSet<CariMutabakatExcel> CariMutabakatExcel { get; set; }
        public virtual DbSet<FaturaBilgileriExcel> FaturaBilgileriExcel { get; set; }
    }
}
